# Generated by Django 5.2 on 2025-05-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='canvas_edited_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/edited/canvas'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
